daemon: "http://localhost:8080"
receivers:
  insecure: "insecure://"
transformations:
  pass: "pass://"
dispatchers:
  log: "log://"
  echo: "echo://webhook-echo:8888"
webhooks:
  - endpoint: "/api"
    receiver: "insecure"
    transformations:
      - "pass"
    dispatchers:
      - "echo"
