receivers:
  passthrough: "passthrough://"
transformations:
  passthrough: "passthrough://"
dispatchers:
  log: "log://"
  echo: "echo://webhook-echo:8888"
webhooks:
  - endpoint: "/echo"
    receiver: "passthrough"
    transformations:
      - "passthrough"
    dispatchers:
      - "echo"
  - endpoint: "/api"
    receiver: "passthrough"
    transformations:
      - "passthrough"
    dispatchers:
      - "log"

